name: "docs"
aliases:
  - "doc2site"
  - "notes"
domain: "docs.roadtotech.me"
description: "Reactive Obsidian & Markdown Documentation Viewer"
visible: true
auth: false
networks:
  - proxy-net
env:
  PROJECT_PATH: "/home/kiskaadee/Brain"
homepage:
  title: "Docs-Viewer"
  group: "Knowledge & Notes"
  icon: "files.png"
  container: "docs"
  weight: 10
